package com.bookstore.entity;
// Generated Oct 3, 2020, 9:34:37 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name = "sach", catalog = "bookstore")
//Lấy toàn bộ sách xuống
@NamedQueries({ @NamedQuery(name = "Sach.findAll", query = "select b from Book b") })
public class Sach implements java.io.Serializable {

	private Integer maSach;
	private Theloaisach theloaisach;
	private String tenSach;
	private long gia;
	private Integer soLuong;
	private String tenTacGia;
	private String hinhAnh;
	private String moTa;
	private int khuyenMai;
	private Date ngayXuatBan;
	private Set<Billcontainsach> billcontainsaches = new HashSet<Billcontainsach>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);

	public Sach() {
	}

	public Sach(long gia, String moTa, int khuyenMai) {
		this.gia = gia;
		this.moTa = moTa;
		this.khuyenMai = khuyenMai;
	}

	public Sach(Theloaisach theloaisach, String tenSach, long gia, Integer soLuong, String tenTacGia, String hinhAnh,
			String moTa, int khuyenMai, Date ngayXuatBan, Set<Billcontainsach> billcontainsaches, Set<Comment> comments,
			Set<Wishlist> wishlists) {
		this.theloaisach = theloaisach;
		this.tenSach = tenSach;
		this.gia = gia;
		this.soLuong = soLuong;
		this.tenTacGia = tenTacGia;
		this.hinhAnh = hinhAnh;
		this.moTa = moTa;
		this.khuyenMai = khuyenMai;
		this.ngayXuatBan = ngayXuatBan;
		this.billcontainsaches = billcontainsaches;
		this.comments = comments;
		this.wishlists = wishlists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "maSach", unique = true, nullable = false)
	public Integer getMaSach() {
		return this.maSach;
	}

	public void setMaSach(Integer maSach) {
		this.maSach = maSach;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loaiSach")
	public Theloaisach getTheloaisach() {
		return this.theloaisach;
	}

	public void setTheloaisach(Theloaisach theloaisach) {
		this.theloaisach = theloaisach;
	}

	@Column(name = "tenSach", length = 65535)
	public String getTenSach() {
		return this.tenSach;
	}

	public void setTenSach(String tenSach) {
		this.tenSach = tenSach;
	}

	@Column(name = "gia", nullable = false, precision = 11, scale = 0)
	public long getGia() {
		return this.gia;
	}

	public void setGia(long gia) {
		this.gia = gia;
	}

	@Column(name = "soLuong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "tenTacGia", length = 65535)
	public String getTenTacGia() {
		return this.tenTacGia;
	}

	public void setTenTacGia(String tenTacGia) {
		this.tenTacGia = tenTacGia;
	}

	@Column(name = "hinhAnh", length = 65535)
	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@Column(name = "moTa", nullable = false)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@Column(name = "khuyenMai", nullable = false)
	public int getKhuyenMai() {
		return this.khuyenMai;
	}

	public void setKhuyenMai(int khuyenMai) {
		this.khuyenMai = khuyenMai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngayXuatBan", length = 10)
	public Date getNgayXuatBan() {
		return this.ngayXuatBan;
	}

	public void setNgayXuatBan(Date ngayXuatBan) {
		this.ngayXuatBan = ngayXuatBan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sach")
	public Set<Billcontainsach> getBillcontainsaches() {
		return this.billcontainsaches;
	}

	public void setBillcontainsaches(Set<Billcontainsach> billcontainsaches) {
		this.billcontainsaches = billcontainsaches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sach")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sach")
	public Set<Wishlist> getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set<Wishlist> wishlists) {
		this.wishlists = wishlists;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.ngayXuatBan = lastUpdateTime;
	}

}
