package com.bookstore.entity;
// Generated Oct 3, 2020, 9:34:37 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theloaisach generated by hbm2java
 */
@Entity
@Table(name = "theloaisach", catalog = "bookstore")
public class Theloaisach implements java.io.Serializable {

	private Integer maTheLoai;
	private String tenTheLoai;
	private Set<Sach> saches = new HashSet<Sach>(0);

	public Theloaisach() {
	}

	public Theloaisach(String tenTheLoai, Set<Sach> saches) {
		this.tenTheLoai = tenTheLoai;
		this.saches = saches;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "maTheLoai", unique = true, nullable = false)
	public Integer getMaTheLoai() {
		return this.maTheLoai;
	}

	public void setMaTheLoai(Integer maTheLoai) {
		this.maTheLoai = maTheLoai;
	}

	@Column(name = "tenTheLoai")
	public String getTenTheLoai() {
		return this.tenTheLoai;
	}

	public void setTenTheLoai(String tenTheLoai) {
		this.tenTheLoai = tenTheLoai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theloaisach")
	public Set<Sach> getSaches() {
		return this.saches;
	}

	public void setSaches(Set<Sach> saches) {
		this.saches = saches;
	}

}
